Fix name of the Cache health result store parameter
spatie/laravel-health pull request #68
Opened 2022-02-03 09:04 UTC by andrzejkupczyk

I needed to figure out why this result store does not work as expected… Hope this fix helps others save some time 😉

2022-02-03 14:05 UTC, freekmurze requested changes
Good catch, but let's solve it differently.

2022-02-03 14:05 UTC, freekmurze commented on config/health.php
> +            'cacheStore' => 'file',
I'm thinking it might be better to make the `store` key work, instead of changing the name.

2022-02-04 09:12 UTC, andrzejkupczyk commented on config/health.php
> +            'cacheStore' => 'file',
It would be better, totally agree. This was my original approach but I was worried about breaking backward compatibility.

I will solve it this way but first please confirm you are sure about it 😉

2022-02-13 13:33 UTC, freekmurze commented on config/health.php
> +            'cacheStore' => 'file',
Yes

2022-02-17 18:59 UTC, andrzejkupczyk commented on config/health.php
> +            'cacheStore' => 'file',
![](https://c.tenor.com/09g131Rr4H0AAAAM/ok-then.gif)

2022-02-20 19:03 UTC, merged

2022-02-20 19:03 UTC, freekmurze commented
Thanks!